runtime: python311

instance_class: F2

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

beta_settings:
  cloud_sql_instances: ski-rent:europe-west1:mqwmee

entrypoint: bash -c "python3 manage.py migrate && gunicorn rental_service.wsgi:application"

env_variables:

  DB_PASSWORD: "Lea1234&"

  DJANGO_SETTINGS_MODULE: "rental_service.settings"