# Generated by Django 6.0.4 on 2026-04-09 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_remove_equipment_created_at_equipment_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='quantity_rented',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='equipment.equipmenttype'),
        ),
    ]
