# Generated by Django 5.1.3 on 2026-05-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='has_sizes',
            field=models.BooleanField(default=True, verbose_name='Есть размеры'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
