# Generated by Django 6.0.4 on 2026-04-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipmentsize'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentsize',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
    ]
