# Generated by Django 6.0.4 on 2026-04-19 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_document_id_alter_client_email_and_more'),
        ('rentals', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='draft', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('signature_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rentals.rental')),
            ],
        ),
    ]
