# Generated by Django 6.0.4 on 2026-04-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_signature_and_contract_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
