# Generated by Django 6.0.4 on 2026-04-28 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_rentalitem_size_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals', to='rentals.discount', verbose_name='Скидка'),
        ),
    ]
