# Generated by Django 5.1.15 on 2026-04-04 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_id'),
        ('rentals', '0002_alter_rental_client_alter_rental_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentals.rental'),
        ),
    ]
