# Generated by Django 6.0.4 on 2026-04-09 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_id'),
        ('rentals', '0003_discount_pricemodifier_alter_rental_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricemodifier',
            options={'verbose_name': 'Модификатор цены'},
        ),
        migrations.AddField(
            model_name='rental',
            name='contract_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('open', 'Открыт'), ('booked', 'Забронирован'), ('rented', 'Арендован'), ('completed', 'Завершён'), ('canceled', 'Отменён')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='days',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rentals.rental'),
        ),
    ]
