# Generated by Django 5.1.3 on 2026-05-12 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_alter_equipment_has_sizes_alter_equipment_quantity_and_more'),
        ('rentals', '0011_delete_smsotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalitem',
            name='size',
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='equipment_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_items', to='equipment.equipmentsize', verbose_name='Размер снаряжения'),
        ),
    ]
